import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  preload: true,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={roboto.className}>
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
//
// Usage of Footer Component:
// - The Footer component is imported and rendered in the RootLayout to ensure it appears at the bottom of every page.
// - This provides consistent branding and copyright info across the app.
//
// Example:
// import Footer from "@/components/footer";
//
// export default function RootLayout({ children }) {
//   return (
//     <html lang="en" className={roboto.className}>
//       <body>
//         <Header />
//         {children}
//         <Footer />
//       </body>
//     </html>
//   );
// }
// -----------------------------------------------------------------------------
